---
- name: Create directory structure for Quarto
  ansible.builtin.file:
    path: "{{ quarto_install_root_dir }}/{{ quarto_version }}"
    state: directory
    mode: '0755'

- name: Download Quarto tar.gz
  ansible.builtin.get_url:
    url: "https://github.com/quarto-dev/quarto-cli/releases/download/v{{ quarto_version }}/quarto-{{ quarto_version }}-linux-amd64.tar.gz"
    dest: "/tmp/quarto-{{ quarto_version }}-linux-amd64.tar.gz"
    mode: '0644'

- name: Extract Quarto tar.gz
  ansible.builtin.unarchive:
    src: "/tmp/quarto-{{ quarto_version }}-linux-amd64.tar.gz"
    dest: "{{ quarto_install_root_dir }}/{{ quarto_version }}"
    remote_src: true
    extra_opts: [--strip-components=1]
