# tasks file
---
- name: include variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "_{{ ansible_distribution_release }}.yml"
    - "_{{ ansible_distribution | lower }}.yml"
    - _default.yml
  tags:
    - configuration

- name: Install Quarto
  ansible.builtin.include_tasks: ./install-quarto.yml
  loop: "{{ quarto_versions }}"
  loop_control:
    loop_var: quarto_version

- name: Create symlink for default Quarto version
  ansible.builtin.file:
    src: "{{ quarto_install_root_dir }}/{{ quarto_default_version }}/bin/quarto"
    dest: "/usr/local/bin/quarto"
    state: link
  when: quarto_default_version | default('') | length > 0
